### ISSUE TITLE
Adduser for Main_Guild and Modmail_Guild

### ISSUE THREAD

**Issue by martinbndr** [modmail-dev/Modmail#3314] opened 2023-10-29 12:00 UTC
### Is your feature request related to a problem? Please elaborate.

Currently, if using a seperate modmail guild, the adduser, removeuser etc command doess not work.

Because the command searches for members/roles in the modmail server. (Also for other commands related to server members etc may broken if using seperate guild)
In most cases members are not in the modmail inbox server as it´s only for server staff private use.

### Describe the solution you'd like

If using a seperate modmail guild, the command should get members/roles from the main_guild.
Maybe adding a toggalble option also be useful then.

### Does your solution involve any of the following?

- [ ] Logviewer
- [ ] New config option

### Describe alternatives you've considered

-

### Who will this benefit?

Group conversations can be used again even if there is a seperate modmail guild set for the inbox.

**Comment by Taaku18** [comment] 2023-11-19 21:37
Thanks for bringing this up, this is definitely not the intended behaviour. We'll fix it in the future! The underlying bug is #3311, I'll close this as a duplicate.

**Closed by Taaku18** 2023-11-19 21:37 UTC
Labels: feature request
