### ISSUE TITLE
[BREAKING] new hosting method

### ISSUE THREAD

**Issue by lorenzo132** [modmail-dev/Modmail#3182] opened 2022-08-27 12:12 UTC
### Bot Version

all

### How are you hosting Modmail?

Other

### Error Logs

-

### Screenshots

-

### Additional Information

There is no sleeping function on Render like heroku offers for the logviewer. The change of hosting requires a merge of both logviewer and bot into 1 repo.

**Comment by StephenDaDev** [comment] 2022-08-27 13:02
Oh boy here we go again

**Comment by Taaku18** [comment] 2023-07-11 23:44
Duplicate of #2849.

**Closed by Taaku18** 2023-07-11 23:44 UTC
Labels: duplicate, feature request
