### ISSUE TITLE
[BUG]: Heroku deploy thows an application error when opening a log.

### ISSUE THREAD

**Issue by flvffywvffy** [modmail-dev/modmail#3220] opened 2022-10-23 21:29 UTC
### Bot Version

4.0.1

### How are you hosting Modmail?

Heroku

### Error Logs

https://hastebin.cc/bemurusehu

### Screenshots

<img width="1439" alt="Screenshot 2022-10-23 at 22 29 12" src="https://user-images.githubusercontent.com/89603987/197419218-48dc0bec-ec26-433b-94c2-d61c0f6a9876.png">

**Comment by sebkuip** [comment] 2022-10-23 21:46
Not a bug. You can't press open app on discord bot. That will just give that error always.

**Comment by flvffywvffy** [comment] 2022-10-23 22:21
> Not a bug. You can't press open app on discord bot. That will just give that error always.

How can I open the logs then?

**Comment by sebkuip** [comment] 2022-10-23 22:40
It's a separate app. It's standalone from the bot and only shares the mongo db

**Comment by StephenDaDev** [comment] 2023-03-12 17:31
There is no bug here, as such, closing.

**Closed by StephenDaDev** 2023-03-12 17:31 UTC
Labels: maybe: bug
