### ISSUE TITLE
Allow custom database name in config

### ISSUE THREAD

**Issue by skybird23333** [modmail-dev/modmail#3280] opened 2023-04-14 10:27 UTC
### Is your feature request related to a problem? Please elaborate.

Currently, when the bot connects to a MongoDB instance it uses the database name `modmail_bot` which is hard coded. This means a new MongoDB instance needs to be created for each instance of the bot.

### Describe the solution you'd like

Allow the database name to be configured via .env, and have the following lines read from .env.

https://github.com/modmail-dev/modmail/blob/b21037cbd794a962569de6240c1d95c13009a64e/core/clients.py#L448

https://github.com/modmail-dev/modmail/blob/b21037cbd794a962569de6240c1d95c13009a64e/core/clients.py#L500

### Does your solution involve any of the following?

- [ ] Logviewer
- [X] New config option

### Describe alternatives you've considered

Haven't thought of any, maybe to edit the source code directly(for users).

### Who will this benefit?

People who need to host multiple modmail instances and don't want to make multiple MongoDB atlases/deploy multiple instances of the server for each bot.

**Comment by raidensakura** [comment] 2023-04-14 10:32
Duplicate of #3191

**Closed** 2023-04-14 10:50 UTC
Labels: feature request
